{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "infisical-entity-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "infisical-entity-operator.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "infisical-entity-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: metrics
      port: 8443
      targetPort: metrics
      protocol: TCP
{{- end }}
