apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "infisical-entity-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "infisical-entity-operator.labels" . | nindent 4 }}
