//go:build !ignore_autogenerated

/*
Copyright 2026 winrarr.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentStatus) DeepCopyInto(out *EnvironmentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentStatus.
func (in *EnvironmentStatus) DeepCopy() *EnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(EnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityMetadata) DeepCopyInto(out *IdentityMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityMetadata.
func (in *IdentityMetadata) DeepCopy() *IdentityMetadata {
	if in == nil {
		return nil
	}
	out := new(IdentityMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityProjectMembershipStatus) DeepCopyInto(out *IdentityProjectMembershipStatus) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]IdentityRoleStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityProjectMembershipStatus.
func (in *IdentityProjectMembershipStatus) DeepCopy() *IdentityProjectMembershipStatus {
	if in == nil {
		return nil
	}
	out := new(IdentityProjectMembershipStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityProjectRoleBinding) DeepCopyInto(out *IdentityProjectRoleBinding) {
	*out = *in
	out.ProjectRef = in.ProjectRef
	if in.RoleSlugs != nil {
		in, out := &in.RoleSlugs, &out.RoleSlugs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityProjectRoleBinding.
func (in *IdentityProjectRoleBinding) DeepCopy() *IdentityProjectRoleBinding {
	if in == nil {
		return nil
	}
	out := new(IdentityProjectRoleBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityRoleStatus) DeepCopyInto(out *IdentityRoleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityRoleStatus.
func (in *IdentityRoleStatus) DeepCopy() *IdentityRoleStatus {
	if in == nil {
		return nil
	}
	out := new(IdentityRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalConnection) DeepCopyInto(out *InfisicalConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalConnection.
func (in *InfisicalConnection) DeepCopy() *InfisicalConnection {
	if in == nil {
		return nil
	}
	out := new(InfisicalConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfisicalConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalConnectionList) DeepCopyInto(out *InfisicalConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfisicalConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalConnectionList.
func (in *InfisicalConnectionList) DeepCopy() *InfisicalConnectionList {
	if in == nil {
		return nil
	}
	out := new(InfisicalConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfisicalConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalConnectionReference) DeepCopyInto(out *InfisicalConnectionReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalConnectionReference.
func (in *InfisicalConnectionReference) DeepCopy() *InfisicalConnectionReference {
	if in == nil {
		return nil
	}
	out := new(InfisicalConnectionReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalConnectionSpec) DeepCopyInto(out *InfisicalConnectionSpec) {
	*out = *in
	if in.AuthSecretRef != nil {
		in, out := &in.AuthSecretRef, &out.AuthSecretRef
		*out = new(SecretKeyReference)
		**out = **in
	}
	if in.UniversalAuth != nil {
		in, out := &in.UniversalAuth, &out.UniversalAuth
		*out = new(UniversalAuthConnectionSpec)
		**out = **in
	}
	if in.RequestTimeout != nil {
		in, out := &in.RequestTimeout, &out.RequestTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalConnectionSpec.
func (in *InfisicalConnectionSpec) DeepCopy() *InfisicalConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(InfisicalConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalConnectionStatus) DeepCopyInto(out *InfisicalConnectionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalConnectionStatus.
func (in *InfisicalConnectionStatus) DeepCopy() *InfisicalConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(InfisicalConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalEnvironment) DeepCopyInto(out *InfisicalEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalEnvironment.
func (in *InfisicalEnvironment) DeepCopy() *InfisicalEnvironment {
	if in == nil {
		return nil
	}
	out := new(InfisicalEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfisicalEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalEnvironmentList) DeepCopyInto(out *InfisicalEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfisicalEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalEnvironmentList.
func (in *InfisicalEnvironmentList) DeepCopy() *InfisicalEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(InfisicalEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfisicalEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalEnvironmentSpec) DeepCopyInto(out *InfisicalEnvironmentSpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	out.ProjectRef = in.ProjectRef
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalEnvironmentSpec.
func (in *InfisicalEnvironmentSpec) DeepCopy() *InfisicalEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(InfisicalEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalEnvironmentStatus) DeepCopyInto(out *InfisicalEnvironmentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalEnvironmentStatus.
func (in *InfisicalEnvironmentStatus) DeepCopy() *InfisicalEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(InfisicalEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalIdentity) DeepCopyInto(out *InfisicalIdentity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalIdentity.
func (in *InfisicalIdentity) DeepCopy() *InfisicalIdentity {
	if in == nil {
		return nil
	}
	out := new(InfisicalIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfisicalIdentity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalIdentityList) DeepCopyInto(out *InfisicalIdentityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfisicalIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalIdentityList.
func (in *InfisicalIdentityList) DeepCopy() *InfisicalIdentityList {
	if in == nil {
		return nil
	}
	out := new(InfisicalIdentityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfisicalIdentityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalIdentitySpec) DeepCopyInto(out *InfisicalIdentitySpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.OrganizationRef != nil {
		in, out := &in.OrganizationRef, &out.OrganizationRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.HasDeleteProtection != nil {
		in, out := &in.HasDeleteProtection, &out.HasDeleteProtection
		*out = new(bool)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make([]IdentityMetadata, len(*in))
		copy(*out, *in)
	}
	if in.RoleSlugs != nil {
		in, out := &in.RoleSlugs, &out.RoleSlugs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProjectRoleBindings != nil {
		in, out := &in.ProjectRoleBindings, &out.ProjectRoleBindings
		*out = make([]IdentityProjectRoleBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalIdentitySpec.
func (in *InfisicalIdentitySpec) DeepCopy() *InfisicalIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(InfisicalIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalIdentityStatus) DeepCopyInto(out *InfisicalIdentityStatus) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]IdentityRoleStatus, len(*in))
		copy(*out, *in)
	}
	if in.ProjectMemberships != nil {
		in, out := &in.ProjectMemberships, &out.ProjectMemberships
		*out = make([]IdentityProjectMembershipStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalIdentityStatus.
func (in *InfisicalIdentityStatus) DeepCopy() *InfisicalIdentityStatus {
	if in == nil {
		return nil
	}
	out := new(InfisicalIdentityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalKubernetesAuth) DeepCopyInto(out *InfisicalKubernetesAuth) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalKubernetesAuth.
func (in *InfisicalKubernetesAuth) DeepCopy() *InfisicalKubernetesAuth {
	if in == nil {
		return nil
	}
	out := new(InfisicalKubernetesAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfisicalKubernetesAuth) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalKubernetesAuthList) DeepCopyInto(out *InfisicalKubernetesAuthList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfisicalKubernetesAuth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalKubernetesAuthList.
func (in *InfisicalKubernetesAuthList) DeepCopy() *InfisicalKubernetesAuthList {
	if in == nil {
		return nil
	}
	out := new(InfisicalKubernetesAuthList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfisicalKubernetesAuthList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalKubernetesAuthSpec) DeepCopyInto(out *InfisicalKubernetesAuthSpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	out.IdentityRef = in.IdentityRef
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedNames != nil {
		in, out := &in.AllowedNames, &out.AllowedNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CACertSecretRef != nil {
		in, out := &in.CACertSecretRef, &out.CACertSecretRef
		*out = new(SecretKeyReference)
		**out = **in
	}
	if in.VerifyTLSCertificate != nil {
		in, out := &in.VerifyTLSCertificate, &out.VerifyTLSCertificate
		*out = new(bool)
		**out = **in
	}
	if in.TokenReviewerJWTSecretRef != nil {
		in, out := &in.TokenReviewerJWTSecretRef, &out.TokenReviewerJWTSecretRef
		*out = new(SecretKeyReference)
		**out = **in
	}
	if in.AccessTokenTrustedIPs != nil {
		in, out := &in.AccessTokenTrustedIPs, &out.AccessTokenTrustedIPs
		*out = make([]KubernetesTrustedIP, len(*in))
		copy(*out, *in)
	}
	if in.AccessTokenTTL != nil {
		in, out := &in.AccessTokenTTL, &out.AccessTokenTTL
		*out = new(int64)
		**out = **in
	}
	if in.AccessTokenMaxTTL != nil {
		in, out := &in.AccessTokenMaxTTL, &out.AccessTokenMaxTTL
		*out = new(int64)
		**out = **in
	}
	if in.AccessTokenNumUsesLimit != nil {
		in, out := &in.AccessTokenNumUsesLimit, &out.AccessTokenNumUsesLimit
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalKubernetesAuthSpec.
func (in *InfisicalKubernetesAuthSpec) DeepCopy() *InfisicalKubernetesAuthSpec {
	if in == nil {
		return nil
	}
	out := new(InfisicalKubernetesAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalKubernetesAuthStatus) DeepCopyInto(out *InfisicalKubernetesAuthStatus) {
	*out = *in
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedNames != nil {
		in, out := &in.AllowedNames, &out.AllowedNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AccessTokenTrustedIPs != nil {
		in, out := &in.AccessTokenTrustedIPs, &out.AccessTokenTrustedIPs
		*out = make([]KubernetesTrustedIP, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalKubernetesAuthStatus.
func (in *InfisicalKubernetesAuthStatus) DeepCopy() *InfisicalKubernetesAuthStatus {
	if in == nil {
		return nil
	}
	out := new(InfisicalKubernetesAuthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalOrganization) DeepCopyInto(out *InfisicalOrganization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalOrganization.
func (in *InfisicalOrganization) DeepCopy() *InfisicalOrganization {
	if in == nil {
		return nil
	}
	out := new(InfisicalOrganization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfisicalOrganization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalOrganizationList) DeepCopyInto(out *InfisicalOrganizationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfisicalOrganization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalOrganizationList.
func (in *InfisicalOrganizationList) DeepCopy() *InfisicalOrganizationList {
	if in == nil {
		return nil
	}
	out := new(InfisicalOrganizationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfisicalOrganizationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalOrganizationSpec) DeepCopyInto(out *InfisicalOrganizationSpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalOrganizationSpec.
func (in *InfisicalOrganizationSpec) DeepCopy() *InfisicalOrganizationSpec {
	if in == nil {
		return nil
	}
	out := new(InfisicalOrganizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalOrganizationStatus) DeepCopyInto(out *InfisicalOrganizationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalOrganizationStatus.
func (in *InfisicalOrganizationStatus) DeepCopy() *InfisicalOrganizationStatus {
	if in == nil {
		return nil
	}
	out := new(InfisicalOrganizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalProject) DeepCopyInto(out *InfisicalProject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalProject.
func (in *InfisicalProject) DeepCopy() *InfisicalProject {
	if in == nil {
		return nil
	}
	out := new(InfisicalProject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfisicalProject) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalProjectList) DeepCopyInto(out *InfisicalProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfisicalProject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalProjectList.
func (in *InfisicalProjectList) DeepCopy() *InfisicalProjectList {
	if in == nil {
		return nil
	}
	out := new(InfisicalProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfisicalProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalProjectSpec) DeepCopyInto(out *InfisicalProjectSpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	if in.OrganizationRef != nil {
		in, out := &in.OrganizationRef, &out.OrganizationRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.ShouldCreateDefaultEnvs != nil {
		in, out := &in.ShouldCreateDefaultEnvs, &out.ShouldCreateDefaultEnvs
		*out = new(bool)
		**out = **in
	}
	if in.HasDeleteProtection != nil {
		in, out := &in.HasDeleteProtection, &out.HasDeleteProtection
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalProjectSpec.
func (in *InfisicalProjectSpec) DeepCopy() *InfisicalProjectSpec {
	if in == nil {
		return nil
	}
	out := new(InfisicalProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalProjectStatus) DeepCopyInto(out *InfisicalProjectStatus) {
	*out = *in
	if in.Environments != nil {
		in, out := &in.Environments, &out.Environments
		*out = make([]EnvironmentStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalProjectStatus.
func (in *InfisicalProjectStatus) DeepCopy() *InfisicalProjectStatus {
	if in == nil {
		return nil
	}
	out := new(InfisicalProjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalUniversalAuth) DeepCopyInto(out *InfisicalUniversalAuth) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalUniversalAuth.
func (in *InfisicalUniversalAuth) DeepCopy() *InfisicalUniversalAuth {
	if in == nil {
		return nil
	}
	out := new(InfisicalUniversalAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfisicalUniversalAuth) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalUniversalAuthList) DeepCopyInto(out *InfisicalUniversalAuthList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfisicalUniversalAuth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalUniversalAuthList.
func (in *InfisicalUniversalAuthList) DeepCopy() *InfisicalUniversalAuthList {
	if in == nil {
		return nil
	}
	out := new(InfisicalUniversalAuthList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfisicalUniversalAuthList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalUniversalAuthSpec) DeepCopyInto(out *InfisicalUniversalAuthSpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	out.IdentityRef = in.IdentityRef
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(UniversalAuthConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	in.ClientSecret.DeepCopyInto(&out.ClientSecret)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalUniversalAuthSpec.
func (in *InfisicalUniversalAuthSpec) DeepCopy() *InfisicalUniversalAuthSpec {
	if in == nil {
		return nil
	}
	out := new(InfisicalUniversalAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalUniversalAuthStatus) DeepCopyInto(out *InfisicalUniversalAuthStatus) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	in.ClientSecret.DeepCopyInto(&out.ClientSecret)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalUniversalAuthStatus.
func (in *InfisicalUniversalAuthStatus) DeepCopy() *InfisicalUniversalAuthStatus {
	if in == nil {
		return nil
	}
	out := new(InfisicalUniversalAuthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesTrustedIP) DeepCopyInto(out *KubernetesTrustedIP) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesTrustedIP.
func (in *KubernetesTrustedIP) DeepCopy() *KubernetesTrustedIP {
	if in == nil {
		return nil
	}
	out := new(KubernetesTrustedIP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UniversalAuthClientSecretSpec) DeepCopyInto(out *UniversalAuthClientSecretSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
	if in.NumUsesLimit != nil {
		in, out := &in.NumUsesLimit, &out.NumUsesLimit
		*out = new(int64)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UniversalAuthClientSecretSpec.
func (in *UniversalAuthClientSecretSpec) DeepCopy() *UniversalAuthClientSecretSpec {
	if in == nil {
		return nil
	}
	out := new(UniversalAuthClientSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UniversalAuthClientSecretStatus) DeepCopyInto(out *UniversalAuthClientSecretStatus) {
	*out = *in
	if in.LastRotatedAt != nil {
		in, out := &in.LastRotatedAt, &out.LastRotatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UniversalAuthClientSecretStatus.
func (in *UniversalAuthClientSecretStatus) DeepCopy() *UniversalAuthClientSecretStatus {
	if in == nil {
		return nil
	}
	out := new(UniversalAuthClientSecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UniversalAuthConfigSpec) DeepCopyInto(out *UniversalAuthConfigSpec) {
	*out = *in
	if in.ClientSecretTrustedIPs != nil {
		in, out := &in.ClientSecretTrustedIPs, &out.ClientSecretTrustedIPs
		*out = make([]UniversalAuthTrustedIP, len(*in))
		copy(*out, *in)
	}
	if in.AccessTokenTrustedIPs != nil {
		in, out := &in.AccessTokenTrustedIPs, &out.AccessTokenTrustedIPs
		*out = make([]UniversalAuthTrustedIP, len(*in))
		copy(*out, *in)
	}
	if in.AccessTokenTTL != nil {
		in, out := &in.AccessTokenTTL, &out.AccessTokenTTL
		*out = new(int64)
		**out = **in
	}
	if in.AccessTokenMaxTTL != nil {
		in, out := &in.AccessTokenMaxTTL, &out.AccessTokenMaxTTL
		*out = new(int64)
		**out = **in
	}
	if in.AccessTokenNumUsesLimit != nil {
		in, out := &in.AccessTokenNumUsesLimit, &out.AccessTokenNumUsesLimit
		*out = new(int64)
		**out = **in
	}
	if in.AccessTokenPeriod != nil {
		in, out := &in.AccessTokenPeriod, &out.AccessTokenPeriod
		*out = new(int64)
		**out = **in
	}
	if in.LockoutEnabled != nil {
		in, out := &in.LockoutEnabled, &out.LockoutEnabled
		*out = new(bool)
		**out = **in
	}
	if in.LockoutThreshold != nil {
		in, out := &in.LockoutThreshold, &out.LockoutThreshold
		*out = new(int64)
		**out = **in
	}
	if in.LockoutDurationSeconds != nil {
		in, out := &in.LockoutDurationSeconds, &out.LockoutDurationSeconds
		*out = new(int64)
		**out = **in
	}
	if in.LockoutCounterResetSeconds != nil {
		in, out := &in.LockoutCounterResetSeconds, &out.LockoutCounterResetSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UniversalAuthConfigSpec.
func (in *UniversalAuthConfigSpec) DeepCopy() *UniversalAuthConfigSpec {
	if in == nil {
		return nil
	}
	out := new(UniversalAuthConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UniversalAuthConfigStatus) DeepCopyInto(out *UniversalAuthConfigStatus) {
	*out = *in
	if in.ClientSecretTrustedIPs != nil {
		in, out := &in.ClientSecretTrustedIPs, &out.ClientSecretTrustedIPs
		*out = make([]UniversalAuthTrustedIP, len(*in))
		copy(*out, *in)
	}
	if in.AccessTokenTrustedIPs != nil {
		in, out := &in.AccessTokenTrustedIPs, &out.AccessTokenTrustedIPs
		*out = make([]UniversalAuthTrustedIP, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UniversalAuthConfigStatus.
func (in *UniversalAuthConfigStatus) DeepCopy() *UniversalAuthConfigStatus {
	if in == nil {
		return nil
	}
	out := new(UniversalAuthConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UniversalAuthConnectionSpec) DeepCopyInto(out *UniversalAuthConnectionSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UniversalAuthConnectionSpec.
func (in *UniversalAuthConnectionSpec) DeepCopy() *UniversalAuthConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(UniversalAuthConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UniversalAuthSecretReference) DeepCopyInto(out *UniversalAuthSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UniversalAuthSecretReference.
func (in *UniversalAuthSecretReference) DeepCopy() *UniversalAuthSecretReference {
	if in == nil {
		return nil
	}
	out := new(UniversalAuthSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UniversalAuthTrustedIP) DeepCopyInto(out *UniversalAuthTrustedIP) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UniversalAuthTrustedIP.
func (in *UniversalAuthTrustedIP) DeepCopy() *UniversalAuthTrustedIP {
	if in == nil {
		return nil
	}
	out := new(UniversalAuthTrustedIP)
	in.DeepCopyInto(out)
	return out
}
