# This rule is not used by the project infisical-entity-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to InfisicalKubernetesAuth resources.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: infisical-entity-operator
    app.kubernetes.io/managed-by: kustomize
  name: infisical-infisicalkubernetesauth-viewer-role
rules:
- apiGroups:
  - infisical.infisical-operator.io
  resources:
  - infisicalkubernetesauths
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infisical.infisical-operator.io
  resources:
  - infisicalkubernetesauths/status
  verbs:
  - get
