---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infisical.infisical-operator.io
  resources:
  - infisicalconnections
  - infisicalidentities
  - infisicalprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infisical.infisical-operator.io
  resources:
  - infisicalconnections/status
  - infisicalidentities/status
  - infisicalprojects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infisical.infisical-operator.io
  resources:
  - infisicalidentities/finalizers
  - infisicalprojects/finalizers
  verbs:
  - update
