apiVersion: v2
name: infisical-entity-operator
description: Kubernetes controllers for declaratively managing Infisical projects, environments, roles, machine identities, and Kubernetes Auth
type: application
version: 0.1.0
appVersion: 0.1.0
kubeVersion: ">=1.29.0-0"
