apiVersion: infisical.infisical-operator.io/v1alpha1
kind: InfisicalIdentityTemplate
metadata:
  name: kubernetes-auth-template
spec:
  connectionRef:
    name: infisical
  organizationRef:
    name: tenant
  authMethod: kubernetes
  kubernetes:
    kubernetesHost: https://kubernetes.default.svc
    caCertSecretRef:
      name: kubernetes-ca
      key: ca.crt
    tokenReviewerJWTSecretRef:
      name: kubernetes-reviewer
      key: token
    verifyTLSCertificate: true
    tokenReviewMode: api
    allowedAudience: infisical
  creationPolicy: CreateOrAdopt
  deletionPolicy: Orphan
